In [1]:
import pandas as pd

In [2]:
dadosolym = pd.read_csv('athlete_events.csv')

In [3]:
alunos = {'Nome':['Ricardo', 'Pedro', 'Roberto', 'Carlos'],
          'Nota':[4,7,5.5,9],
           'Aprovado':['Não','Sim','Não','Sim']}

In [4]:
#Comando para criar um dataframe com os dados da biblioteca acima
dataframe = pd.DataFrame(alunos)

In [5]:
print(dataframe)

      Nome  Nota Aprovado
0  Ricardo   4.0      Não
1    Pedro   7.0      Sim
2  Roberto   5.5      Não
3   Carlos   9.0      Sim


In [6]:
#comando 'Series' para criar um vetor unidimensional
objeto1 = pd.Series([2,6,9,10,5])
print(objeto1)

0     2
1     6
2     9
3    10
4     5
dtype: int64


In [10]:
#Mostrando a diferença entre 'Series' e 'Array'
import numpy as np
array1 = np.array([6,12,2,9,10])
array2 = np.array([(2,6,9,10,5),(6,12,2,9,10)])

print(array1)
print(array2)

[ 6 12  2  9 10]
[[ 2  6  9 10  5]
 [ 6 12  2  9 10]]


In [14]:
#converter o array1 em um vetor
objeto2 = pd.Series(array1)
print(objeto2)

0     6
1    12
2     2
3     9
4    10
dtype: int32


In [15]:
#Aula 13

In [16]:
alunosDIC = {'Nome':['Ricardo', 'Pedro', 'Roberto', 'Carlos'],
          'Nota':[4,7,5.5,9],
           'Aprovado':['Não','Sim','Não','Sim']}

In [19]:
alunosDF = pd.DataFrame(alunosDIC)

In [20]:
print(alunosDF)

      Nome  Nota Aprovado
0  Ricardo   4.0      Não
1    Pedro   7.0      Sim
2  Roberto   5.5      Não
3   Carlos   9.0      Sim


In [21]:
alunosDF.head()

Nome  Nota Aprovado
0  Ricardo   4.0      Não
1    Pedro   7.0      Sim
2  Roberto   5.5      Não
3   Carlos   9.0      Sim

In [22]:
# Comando .shape informa nr linhas e nr colunas
alunosDF.shape

(4, 3)

In [23]:
#função .describe analise descritiva
alunosDF.describe()

Nota
count  4.000000
mean   6.375000
std    2.136001
min    4.000000
25%    5.125000
50%    6.250000
75%    7.500000
max    9.000000

In [24]:
#aula 14

In [25]:
print(alunosDF)

      Nome  Nota Aprovado
0  Ricardo   4.0      Não
1    Pedro   7.0      Sim
2  Roberto   5.5      Não
3   Carlos   9.0      Sim


In [26]:
#chamar uma coluna específica do dataset
alunosDF['Nome']

0    Ricardo
1      Pedro
2    Roberto
3     Carlos
Name: Nome, dtype: object

In [31]:
#Como chamar uma linha (índice) específica
alunosDF.loc[[0,3]]

Nome  Nota Aprovado
0  Ricardo   4.0      Não
3   Carlos   9.0      Sim

In [33]:
#Como chamar uma linha (índice) específica do 0 ao 2
alunosDF.loc[0:2]

Nome  Nota Aprovado
0  Ricardo   4.0      Não
1    Pedro   7.0      Sim
2  Roberto   5.5      Não

In [35]:
#Localizar um dado específico no data frame e retornar a busca
alunosDF.loc[alunosDF['Nome']=='Pedro']

Nome  Nota Aprovado
1  Pedro   7.0      Sim

In [36]:
#Aula 15

In [37]:
#filtrar as linhas de 0 a 2
alunosDF.loc[0:2]

Nome  Nota Aprovado
0  Ricardo   4.0      Não
1    Pedro   7.0      Sim
2  Roberto   5.5      Não

In [38]:
#Criar no dataframe a partir de uma consulta
primeiraslinhas = alunosDF.loc[0:2]
print(primeiraslinhas)

      Nome  Nota Aprovado
0  Ricardo   4.0      Não
1    Pedro   7.0      Sim
2  Roberto   5.5      Não


In [39]:
#Selecionar dados por exclusão de condição
#Condição !=4 trouxe todos os valores exceto 4

novoDF = alunosDF.loc[alunosDF['Nota']!=4]
print(novoDF)

      Nome  Nota Aprovado
1    Pedro   7.0      Sim
2  Roberto   5.5      Não
3   Carlos   9.0      Sim


In [40]:
#Selecionar dados por exclusão de condição
#Condição !=4 trouxe todos os valores exceto 4

reprovados = alunosDF.loc[alunosDF['Aprovado']!='Sim']
print(reprovados)

      Nome  Nota Aprovado
0  Ricardo   4.0      Não
2  Roberto   5.5      Não
